// frontend/src/components/BaselineManager.jsx
import React, { useState, useEffect, useRef } from 'react';
import { getBaselines, uploadBaseline, deleteBaseline, getScreenshotUrl } from '../api';
import { Upload, Trash2, Globe, Monitor, Smartphone, Tablet, ChevronLeft, Loader2, Image as ImageIcon, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function BaselineManager() {
    const [domain, setDomain] = useState('');
    const [baselines, setBaselines] = useState([]);
    const [loading, setLoading] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [error, setError] = useState(null);
    const fileInputRefs = useRef({});

    // Form state
    const [routeName, setRouteName] = useState('home');
    const [viewport, setViewport] = useState('Desktop');
    const [file, setFile] = useState(null);

    const loadBaselines = async () => {
        if (!domain) return;
        setLoading(true);
        setError(null);
        try {
            const data = await getBaselines(domain);
            setBaselines(data);
        } catch (err) {
            setError('Failed to load baselines');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        const timer = setTimeout(() => {
            if (domain) {
                let sanitizedDomain = domain;
                try {
                    if (domain.includes('://')) {
                        sanitizedDomain = new URL(domain).hostname;
                        setDomain(sanitizedDomain);
                    }
                } catch (e) { }
                loadBaselines();
            }
        }, 500);
        return () => clearTimeout(timer);
    }, [domain]);

    const handleUpload = async (e) => {
        e.preventDefault();
        if (!file || !domain || !routeName || !viewport) {
            alert('Please fill all fields');
            return;
        }

        setUploading(true);
        try {
            await uploadBaseline(domain, routeName, viewport, file);
            setFile(null);
            // Reset file input
            e.target.reset();
            loadBaselines();
        } catch (err) {
            alert('Upload failed: ' + (err.response?.data?.error || err.message));
        } finally {
            setUploading(false);
        }
    };

    const handleDelete = async (filename) => {
        if (!window.confirm('Delete this baseline?')) return;
        try {
            await deleteBaseline(domain, filename);
            loadBaselines();
        } catch (err) {
            alert('Delete failed');
        }
    };

    const handleReplace = (filename) => {
        // Trigger file input for this specific baseline
        if (fileInputRefs.current[filename]) {
            fileInputRefs.current[filename].click();
        }
    };

    const handleReplaceFile = async (filename, file) => {
        if (!file) return;

        // Extract route name and viewport from filename
        // Format: routeName-viewport-fullpage.png
        const parts = filename.replace('-fullpage.png', '').split('-');
        const viewport = parts[parts.length - 1]; // Last part is viewport
        const routeName = parts.slice(0, -1).join('-'); // Everything before viewport

        setUploading(true);
        try {
            await uploadBaseline(domain, routeName, viewport, file);
            loadBaselines();
        } catch (err) {
            alert('Replace failed: ' + (err.response?.data?.error || err.message));
        } finally {
            setUploading(false);
        }
    };

    return (
        <div className="max-w-6xl mx-auto p-6">
            <Link to="/" className="flex items-center gap-2 text-gray-600 mb-6 hover:text-blue-600">
                <ChevronLeft size={20} /> Back to Dashboard
            </Link>

            <div className="flex flex-col md:flex-row gap-8">
                {/* Sidebar: Upload Form */}
                <div className="md:w-1/3">
                    <div className="bg-white p-6 rounded-xl shadow-lg border border-slate-100 sticky top-6">
                        <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                            <Upload className="text-blue-600" /> Upload Baseline
                        </h2>

                        <form onSubmit={handleUpload} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Domain</label>
                                <input
                                    type="text"
                                    placeholder="example.com"
                                    value={domain}
                                    onChange={(e) => setDomain(e.target.value)}
                                    className="w-full p-2 border border-gray-300 rounded-md text-sm"
                                    required
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Route Name</label>
                                <input
                                    type="text"
                                    placeholder="home, about, etc."
                                    value={routeName}
                                    onChange={(e) => setRouteName(e.target.value)}
                                    className="w-full p-2 border border-gray-300 rounded-md text-sm"
                                    required
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Viewport</label>
                                <select
                                    value={viewport}
                                    onChange={(e) => setViewport(e.target.value)}
                                    className="w-full p-2 border border-gray-300 rounded-md text-sm"
                                >
                                    <option value="Desktop">Desktop (1920x1080)</option>
                                    <option value="Tablet">Tablet (768x1024)</option>
                                    <option value="Mobile">Mobile (375x667)</option>
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Image File</label>
                                <input
                                    type="file"
                                    accept="image/png"
                                    onChange={(e) => setFile(e.target.files[0])}
                                    className="w-full text-xs text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100"
                                    required
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={uploading || !domain}
                                className="w-full bg-blue-600 text-white py-2 rounded-md font-semibold hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2 transition-colors"
                            >
                                {uploading ? <Loader2 className="animate-spin" size={18} /> : <Upload size={18} />}
                                {uploading ? 'Uploading...' : 'Save Baseline'}
                            </button>
                        </form>

                        <div className="mt-6 p-4 bg-amber-50 rounded-lg border border-amber-100 italic text-xs text-amber-800">
                            Note: Uploaded images will be used as the new ground truth for visual comparisons.
                        </div>
                    </div>
                </div>

                {/* Main Content: Baseline List */}
                <div className="md:w-2/3">
                    <div className="bg-white p-6 rounded-xl shadow-lg border border-slate-100 min-h-[500px]">
                        <div className="flex justify-between items-center mb-6">
                            <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
                                <ImageIcon className="text-slate-600" /> Existing Baselines
                            </h2>
                            {domain && (
                                <span className="bg-slate-100 text-slate-600 px-3 py-1 rounded-full text-xs font-mono">
                                    {domain}
                                </span>
                            )}
                        </div>

                        {!domain ? (
                            <div className="flex flex-col items-center justify-center h-80 text-gray-400">
                                <Globe size={48} className="mb-4 opacity-20" />
                                <p>Enter a domain to manage its baselines</p>
                            </div>
                        ) : loading ? (
                            <div className="flex justify-center items-center h-80">
                                <Loader2 className="animate-spin text-blue-600" size={32} />
                            </div>
                        ) : baselines.length === 0 ? (
                            <div className="flex flex-col items-center justify-center h-80 text-gray-400">
                                <ImageIcon size={48} className="mb-4 opacity-20" />
                                <p>No baselines found for this domain</p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                {baselines.map((bl) => (
                                    <div key={bl.filename} className="group relative border rounded-lg overflow-hidden hover:shadow-md transition-shadow">
                                        <div className="aspect-video bg-slate-100 overflow-hidden">
                                            <img
                                                src={getScreenshotUrl(bl.path)}
                                                alt={bl.filename}
                                                className="w-full h-full object-cover cursor-pointer hover:scale-105 transition-transform"
                                                onClick={() => window.open(getScreenshotUrl(bl.path), '_blank')}
                                            />
                                        </div>
                                        <div className="p-3 bg-white flex justify-between items-center">
                                            <div className="truncate pr-2">
                                                <div className="text-sm font-bold truncate text-slate-800">{bl.filename}</div>
                                                <div className="flex items-center gap-2 mt-1">
                                                    {bl.filename.includes('desktop') ? <Monitor size={12} className="text-slate-400" /> :
                                                        bl.filename.includes('tablet') ? <Tablet size={12} className="text-slate-400" /> :
                                                            <Smartphone size={12} className="text-slate-400" />}
                                                    <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">
                                                        {bl.filename.split('-')[1]}
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="flex gap-1">
                                                {/* Hidden file input for replace */}
                                                <input
                                                    ref={el => fileInputRefs.current[bl.filename] = el}
                                                    type="file"
                                                    accept="image/png"
                                                    onChange={(e) => handleReplaceFile(bl.filename, e.target.files[0])}
                                                    className="hidden"
                                                />
                                                <button
                                                    onClick={() => handleReplace(bl.filename)}
                                                    className="p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-full transition-colors"
                                                    title="Replace baseline"
                                                    disabled={uploading}
                                                >
                                                    <RefreshCw size={16} className={uploading ? 'animate-spin' : ''} />
                                                </button>
                                                <button
                                                    onClick={() => handleDelete(bl.filename)}
                                                    className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-full transition-colors"
                                                    title="Delete baseline"
                                                >
                                                    <Trash2 size={16} />
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

// angular-frontend/src/app/components/baseline-manager/baseline-manager.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { LucideAngularModule, Upload, Trash2, Globe, Monitor, Smartphone, Tablet, ChevronLeft, Loader2, Image as ImageIcon, RefreshCw } from 'lucide-angular';
import { Subject, Subscription } from 'rxjs';
import { debounceTime, distinctUntilChanged } from 'rxjs/operators';

@Component({
    selector: 'app-baseline-manager',
    standalone: true,
    imports: [CommonModule, FormsModule, RouterModule, LucideAngularModule],
    templateUrl: './baseline-manager.component.html'
})
export class BaselineManagerComponent implements OnInit, OnDestroy {
    domain = '';
    baselines: any[] = [];
    loading = false;
    uploading = false;
    error: string | null = null;

    // Form state
    routeName = 'home';
    viewport = 'Desktop';
    file: File | null = null;

    private domainSubject = new Subject<string>();
    private domainSubscription?: Subscription;

    constructor(private apiService: ApiService) { }

    ngOnInit() {
        this.domainSubscription = this.domainSubject.pipe(
            debounceTime(500),
            distinctUntilChanged()
        ).subscribe(domain => {
            this.handleDomainChange(domain);
        });
    }

    ngOnDestroy() {
        this.domainSubscription?.unsubscribe();
    }

    onDomainInput() {
        this.domainSubject.next(this.domain);
    }

    handleDomainChange(domain: string) {
        if (!domain) return;
        let sanitizedDomain = domain;
        try {
            if (domain.includes('://')) {
                sanitizedDomain = new URL(domain).hostname;
                this.domain = sanitizedDomain;
            }
        } catch (e) { }
        this.loadBaselines();
    }

    loadBaselines() {
        if (!this.domain) return;
        this.loading = true;
        this.error = null;
        this.apiService.getBaselines(this.domain).subscribe({
            next: (data) => {
                this.baselines = data;
                this.loading = false;
            },
            error: (err) => {
                this.error = 'Failed to load baselines';
                console.error(err);
                this.loading = false;
            }
        });
    }

    onFileSelected(event: any) {
        this.file = event.target.files[0];
    }

    handleUpload(form: any) {
        if (!this.file || !this.domain || !this.routeName || !this.viewport) {
            alert('Please fill all fields');
            return;
        }

        this.uploading = true;
        this.apiService.uploadBaseline(this.domain, this.routeName, this.viewport, this.file).subscribe({
            next: () => {
                this.file = null;
                form.reset();
                this.routeName = 'home';
                this.viewport = 'Desktop';
                this.uploading = false;
                this.loadBaselines();
            },
            error: (err) => {
                alert('Upload failed: ' + (err.error?.error || err.message));
                this.uploading = false;
            }
        });
    }

    handleDelete(filename: string) {
        if (!window.confirm('Delete this baseline?')) return;
        this.apiService.deleteBaseline(this.domain, filename).subscribe({
            next: () => this.loadBaselines(),
            error: (err) => alert('Delete failed')
        });
    }

    triggerReplace(filename: string) {
        const input = document.getElementById('replace-' + filename) as HTMLInputElement;
        if (input) input.click();
    }

    handleReplaceFile(filename: string, event: any) {
        const file = event.target.files[0];
        if (!file) return;

        // Extract route name and viewport from filename
        // Format: routeName-viewport-fullpage.png
        const parts = filename.replace('-fullpage.png', '').split('-');
        const viewport = parts[parts.length - 1];
        const routeName = parts.slice(0, -1).join('-');

        this.uploading = true;
        this.apiService.uploadBaseline(this.domain, routeName, viewport, file).subscribe({
            next: () => {
                this.uploading = false;
                this.loadBaselines();
            },
            error: (err) => {
                alert('Replace failed: ' + (err.error?.error || err.message));
                this.uploading = false;
            }
        });
    }

    getScreenshotUrl(path: string): string {
        return this.apiService.getScreenshotUrl(path);
    }

    openScreenshot(path: string) {
        window.open(this.getScreenshotUrl(path), '_blank');
    }

    getViewportIcon(filename: string): string {
        if (filename.toLowerCase().includes('desktop')) return 'monitor';
        if (filename.toLowerCase().includes('tablet')) return 'tablet';
        return 'smartphone';
    }
}

<div class="space-y-12 animate-fade-in">
    <div class="flex items-center justify-between">
        <a routerLink="/" class="nav-link bg-white shadow-sm border border-slate-100">
            <lucide-icon name="chevron-left" [size]="18"></lucide-icon>
            Back to Dashboard
        </a>
        <div class="text-right">
            <h1 class="text-3xl font-extrabold text-slate-900 tracking-tight">Baseline Manager</h1>
            <p class="text-slate-500 text-sm">Manage ground truth images for visual comparison.</p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row gap-12">
        <!-- Sidebar: Upload Form -->
        <div class="lg:w-80 shrink-0">
            <div class="glass-card p-8 space-y-8 sticky top-32">
                <div class="flex items-center gap-3">
                    <div class="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600">
                        <lucide-icon name="upload" [size]="20"></lucide-icon>
                    </div>
                    <h2 class="text-lg font-bold text-slate-900">Add New</h2>
                </div>

                <form #uploadForm="ngForm" (submit)="handleUpload(uploadForm)" class="space-y-5">
                    <div class="space-y-1.5">
                        <label
                            class="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Domain</label>
                        <input type="text" name="domain" placeholder="example.com" [(ngModel)]="domain"
                            (input)="onDomainInput()" class="input-premium py-2.5 text-sm" required />
                    </div>

                    <div class="space-y-1.5">
                        <label class="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Route</label>
                        <input type="text" name="routeName" placeholder="home" [(ngModel)]="routeName"
                            class="input-premium py-2.5 text-sm" required />
                    </div>

                    <div class="space-y-1.5">
                        <label
                            class="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Viewport</label>
                        <select name="viewport" [(ngModel)]="viewport" class="input-premium py-2.5 text-sm bg-slate-50">
                            <option value="Desktop">Desktop (1920x1080)</option>
                            <option value="Tablet">Tablet (768x1024)</option>
                            <option value="Mobile">Mobile (375x667)</option>
                        </select>
                    </div>

                    <div class="space-y-3">
                        <label class="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1">Image
                            File</label>
                        <div class="relative group">
                            <input type="file" accept="image/png" (change)="onFileSelected($event)"
                                class="w-full text-xs text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-[10px] file:font-bold file:bg-slate-900 file:text-white hover:file:bg-slate-800 transition-all cursor-pointer"
                                required />
                        </div>
                    </div>

                    <button type="submit" [disabled]="uploading || !domain || !file"
                        class="btn-primary w-full py-4 text-sm shadow-indigo-100">
                        <lucide-icon *ngIf="uploading" name="loader-2" class="animate-spin" [size]="18"></lucide-icon>
                        <lucide-icon *ngIf="!uploading" name="upload" [size]="18"></lucide-icon>
                        {{ uploading ? 'Uploading...' : 'Save Baseline' }}
                    </button>
                </form>

                <div class="p-4 bg-amber-50/50 rounded-xl border border-amber-100/50 flex gap-3">
                    <lucide-icon name="shield" class="text-amber-600 shrink-0" [size]="16"></lucide-icon>
                    <p class="text-[10px] text-amber-800 leading-relaxed font-medium">
                        Uploaded images become the "ground truth" for future visual comparisons.
                    </p>
                </div>
            </div>
        </div>

        <!-- Main Content -->
        <div class="flex-1 space-y-8">
            <div class="flex items-center justify-between">
                <div class="flex items-center gap-2">
                    <lucide-icon name="image" class="text-indigo-600" [size]="20"></lucide-icon>
                    <h2 class="text-xl font-bold text-slate-900">Current Baselines</h2>
                    <span *ngIf="domain"
                        class="ml-2 px-2 py-0.5 rounded-md bg-slate-100 text-slate-500 text-[10px] font-bold uppercase tracking-widest border border-slate-200">
                        {{ domain }}
                    </span>
                </div>
                <button *ngIf="domain" (click)="loadBaselines()"
                    class="p-2 rounded-lg hover:bg-slate-100 text-slate-400 transition-colors">
                    <lucide-icon name="refresh-cw" [size]="18" [class]="loading ? 'animate-spin' : ''"></lucide-icon>
                </button>
            </div>

            <!-- List States -->
            <div *ngIf="!domain" class="py-32 premium-card flex flex-col items-center justify-center text-slate-300">
                <lucide-icon name="globe" [size]="64" class="mb-4 opacity-10"></lucide-icon>
                <p class="font-bold text-slate-400">Search for a domain to start</p>
                <p class="text-[10px] uppercase font-bold tracking-widest mt-1">management panel</p>
            </div>

            <div *ngIf="domain && loading" class="py-32 flex justify-center">
                <lucide-icon name="loader-2" class="animate-spin text-indigo-600" [size]="48"></lucide-icon>
            </div>

            <div *ngIf="domain && !loading && baselines.length === 0"
                class="py-32 premium-card flex flex-col items-center justify-center text-slate-300">
                <lucide-icon name="image" [size]="64" class="mb-4 opacity-10"></lucide-icon>
                <p class="font-bold text-slate-400">No baselines configured yet</p>
                <p class="text-xs mt-1">Upload an image on the left to create one.</p>
            </div>

            <div *ngIf="domain && !loading && baselines.length > 0"
                class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
                <div *ngFor="let bl of baselines" class="premium-card overflow-hidden group">
                    <div class="aspect-video bg-slate-100 relative overflow-hidden flex items-center justify-center">
                        <img [src]="getScreenshotUrl(bl.path)" [alt]="bl.filename"
                            class="w-full h-full object-cover cursor-zoom-in group-hover:scale-105 transition-transform duration-500"
                            (click)="openScreenshot(bl.path)" />
                        <div
                            class="absolute inset-0 bg-slate-900/0 group-hover:bg-slate-900/10 transition-colors pointer-events-none">
                        </div>
                        <div
                            class="absolute top-2 right-2 px-2 py-1 bg-white/90 backdrop-blur rounded-lg text-[10px] font-bold text-slate-900 shadow-sm border border-slate-200/50">
                            {{ bl.filename.split('-')[bl.filename.split('-').length - 2].toUpperCase() }}
                        </div>
                    </div>
                    <div class="p-4 flex justify-between items-center">
                        <div class="truncate max-w-[120px]">
                            <div class="text-xs font-bold text-slate-800 truncate">{{ bl.filename }}</div>
                            <div class="flex items-center gap-1.5 mt-1">
                                <lucide-icon [name]="getViewportIcon(bl.filename)" [size]="10"
                                    class="text-indigo-400"></lucide-icon>
                                <span
                                    class="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Verified</span>
                            </div>
                        </div>
                        <div class="flex gap-1">
                            <input [id]="'replace-' + bl.filename" type="file" accept="image/png"
                                (change)="handleReplaceFile(bl.filename, $event)" class="hidden" />
                            <button (click)="triggerReplace(bl.filename)"
                                class="w-9 h-9 flex items-center justify-center text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-xl transition-all"
                                title="Update baseline" [disabled]="uploading">
                                <lucide-icon name="refresh-cw" [size]="16"
                                    [class]="uploading ? 'animate-spin' : ''"></lucide-icon>
                            </button>
                            <button (click)="handleDelete(bl.filename)"
                                class="w-9 h-9 flex items-center justify-center text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-xl transition-all"
                                title="Delete image">
                                <lucide-icon name="trash-2" [size]="16"></lucide-icon>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
