// angular-frontend/src/app/components/report-detail/report-detail.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { LucideAngularModule, ArrowLeft, CheckCircle, XCircle, Smartphone, Download, Trash2, Loader2, Image as ImageIcon, Monitor, Tablet, ExternalLink, Globe, Shield } from 'lucide-angular';
import { Subscription, of } from 'rxjs';
import { delay, catchError, map, finalize } from 'rxjs/operators';

@Component({
    selector: 'app-report-detail',
    standalone: true,
    imports: [CommonModule, RouterModule, LucideAngularModule],
    templateUrl: './report-detail.component.html'
})
export class ReportDetailComponent implements OnInit, OnDestroy {
    report: any = null;
    loading = true;
    error: string | null = null;
    private routeSub?: Subscription;

    constructor(
        private route: ActivatedRoute,
        private router: Router,
        private apiService: ApiService,
        private cdr: ChangeDetectorRef
    ) { }

    ngOnInit() {
        // Clear state on init
        this.loading = true;
        this.report = null;
        this.error = null;

        // Use observable for params
        this.routeSub = this.route.paramMap.subscribe(params => {
            const id = params.get('id');
            if (id) {
                this.loadReport(id);
            } else {
                this.loading = false;
                this.cdr.detectChanges();
            }
        });

        // Safety timeout: 15 seconds
        setTimeout(() => {
            if (this.loading) {
                console.warn('Report loading timed out.');
                this.loading = false;
                this.cdr.detectChanges();
            }
        }, 15000);
    }

    ngOnDestroy() {
        this.routeSub?.unsubscribe();
    }

    loadReport(id: string) {
        this.loading = true;
        this.error = null;
        this.report = null;
        this.cdr.detectChanges();

        this.apiService.getReport(id).pipe(
            finalize(() => {
                // Ensure loading is set to false in the next tick
                setTimeout(() => {
                    this.loading = false;
                    this.cdr.detectChanges();
                }, 0);
            })
        ).subscribe({
            next: (data) => {
                if (data) {
                    this.report = data;
                } else {
                    this.error = 'Report not found';
                }
            },
            error: (err) => {
                console.error('Failed to load report:', err);
                this.error = 'Failed to retrieve report data';
                this.report = null;
            }
        });
    }

    get results(): any[] {
        const data = this.report?.results || this.report?.tests || [];
        return Array.isArray(data) ? data : [];
    }

    handleDownload() {
        if (!this.report?.id) return;
        this.apiService.downloadReport(this.report.id).subscribe({
            next: (blob) => {
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `report-${this.report.id}.zip`;
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
                document.body.removeChild(a);
            },
            error: (err) => {
                console.error('Download failed:', err);
                alert('Failed to download report');
            }
        });
    }

    handleDelete() {
        if (!this.report?.id || !window.confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
            return;
        }

        this.apiService.deleteReport(this.report.id).subscribe({
            next: () => {
                alert('Report deleted successfully');
                this.router.navigate(['/']);
            },
            error: (err) => {
                console.error('Delete failed:', err);
                alert('Failed to delete report');
            }
        });
    }

    getScreenshotUrl(filename: string): string {
        return this.apiService.getScreenshotUrl(filename);
    }

    openScreenshot(filename: string) {
        if (filename) {
            window.open(this.getScreenshotUrl(filename), '_blank');
        }
    }

    getTotalViewports(): number {
        return this.results.reduce((acc: number, r: any) => acc + (r?.viewports?.length || 0), 0) || 0;
    }

    getTotalScreenshots(): number {
        return this.results.reduce((acc: number, r: any) => {
            const viewports = r?.viewports || [];
            return acc + viewports.reduce((sum: number, vp: any) => sum + 1 + (vp?.components?.length || 0), 0);
        }, 0) || 0;
    }

    getTotalComponents(): number {
        return this.results.reduce((acc: number, r: any) => {
            const viewports = r?.viewports || [];
            return acc + viewports.reduce((sum: number, vp: any) => sum + (vp?.components?.length || 0), 0);
        }, 0) || 0;
    }

    getTotalPixelsChanged(): number {
        return this.results.reduce((acc: number, r: any) => {
            const viewports = r?.viewports || [];
            return acc + viewports.reduce((sum: number, vp: any) => {
                let count = (vp?.fullPage?.diffPixels || 0);
                count += (vp?.components || []).reduce((cSum: number, c: any) => cSum + (c?.diffPixels || 0), 0);
                return sum + count;
            }, 0);
        }, 0) || 0;
    }

    getStatusColor(status: string): string {
        if (!status) return 'bg-slate-100 text-slate-500 border-slate-200';
        const s = status.toLowerCase();
        if (s === 'pass') return 'bg-emerald-100 text-emerald-700 border-emerald-200';
        if (s === 'fail') return 'bg-red-100 text-red-700 border-red-200';
        if (s.includes('baseline')) return 'bg-indigo-100 text-indigo-700 border-indigo-200';
        return 'bg-slate-100 text-slate-500 border-slate-200';
    }

    formatStatus(status: string): string {
        if (!status) return 'UNKNOWN';
        try {
            return status.toString().replace(/_/g, ' ').toUpperCase();
        } catch (e) {
            return 'UNKNOWN';
        }
    }
}

<div class="space-y-12 animate-fade-in pb-20">
    <!-- Breadcrumbs -->
    <div class="flex items-center justify-between">
        <a routerLink="/" class="nav-link bg-white shadow-sm border border-slate-100">
            <lucide-icon name="arrow-left" [size]="18"></lucide-icon>
            Back to Home
        </a>
        <div class="flex items-center gap-2">
            <div class="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)]"></div>
            <span class="text-xs font-bold text-slate-500 uppercase tracking-widest">Report Analysis</span>
        </div>
    </div>

    <div *ngIf="loading" class="py-32 flex flex-col items-center justify-center space-y-4">
        <lucide-icon name="loader-2" class="animate-spin text-indigo-600" [size]="48"></lucide-icon>
        <p class="text-slate-400 font-medium">Crunching pixel data...</p>
    </div>

    <div *ngIf="!loading && !report"
        class="bg-white p-12 rounded-3xl shadow-xl border border-red-100 text-center space-y-6">
        <div class="w-20 h-20 bg-red-50 text-red-500 rounded-full flex items-center justify-center mx-auto">
            <lucide-icon name="x-circle" [size]="40"></lucide-icon>
        </div>
        <div>
            <h2 class="text-2xl font-bold text-slate-800">Report Not Found</h2>
            <p class="text-slate-500 mt-2">The record might have been cleared or the ID is invalid.</p>
        </div>
        <a routerLink="/" class="btn-primary inline-flex">Go Home</a>
    </div>

    <ng-container *ngIf="!loading && report">
        <!-- Hero Header -->
        <div class="glass-card shadow-2xl overflow-hidden">
            <div class="bg-slate-900 p-10 overflow-hidden relative">
                <!-- Abstract Glow -->
                <div
                    class="absolute top-0 right-0 w-64 h-64 bg-indigo-500/20 blur-[80px] rounded-full translate-x-1/2 -translate-y-1/2">
                </div>

                <div class="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
                    <div class="space-y-4">
                        <div class="flex items-center gap-3">
                            <div
                                class="w-12 h-12 bg-indigo-500/20 rounded-2xl flex items-center justify-center text-indigo-400 border border-indigo-400/20">
                                <lucide-icon name="globe" [size]="24"></lucide-icon>
                            </div>
                            <div>
                                <h1 class="text-4xl font-black text-white tracking-tight">{{ report.site }}</h1>
                                <p class="text-indigo-300 font-medium opacity-80 mt-1">{{ report.url }}</p>
                            </div>
                        </div>
                        <div class="flex flex-wrap gap-4 pt-2">
                            <div
                                class="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-xs font-bold text-slate-300">
                                <lucide-icon name="clock" [size]="14" class="text-indigo-400"></lucide-icon>
                                {{ report.timestamp | date:'MMM d, HH:mm' }}
                            </div>
                            <div
                                class="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-xs font-bold text-slate-300">
                                <lucide-icon name="shield" [size]="14" class="text-emerald-400"></lucide-icon>
                                {{ report.duration || '0s' }} analysis
                            </div>
                        </div>
                    </div>

                    <div class="flex gap-3 w-full md:w-auto">
                        <button (click)="handleDownload()"
                            class="btn-primary flex-1 md:flex-none py-3 shadow-none bg-indigo-500 hover:bg-indigo-400">
                            <lucide-icon name="download" [size]="18"></lucide-icon> Export ZIP
                        </button>
                        <button (click)="handleDelete()"
                            class="btn-secondary flex-1 md:flex-none py-3 border-white/10 bg-white/5 text-white hover:bg-red-500 hover:border-red-500 transition-all">
                            <lucide-icon name="trash-2" [size]="18"></lucide-icon>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Dashboard Style Stats -->
            <div
                class="grid grid-cols-2 lg:grid-cols-4 divide-x divide-slate-100 p-1 border-t border-slate-100 bg-white">
                <div class="p-8 text-center space-y-1">
                    <div class="text-3xl font-black text-slate-800 tracking-tighter">{{ results.length }}</div>
                    <div class="text-[10px] uppercase font-bold text-slate-400 tracking-widest">Target Routes</div>
                </div>
                <div class="p-8 text-center space-y-1 border-l md:border-l-0">
                    <div class="text-3xl font-black text-slate-800 tracking-tighter">{{ getTotalViewports() }}</div>
                    <div class="text-[10px] uppercase font-bold text-slate-400 tracking-widest">Active Viewports</div>
                </div>
                <div class="p-8 text-center space-y-1 border-t md:border-t-0">
                    <div class="text-3xl font-black text-slate-800 tracking-tighter text-indigo-600">{{
                        getTotalScreenshots() }}</div>
                    <div class="text-[10px] uppercase font-bold text-slate-400 tracking-widest">Total Captures</div>
                </div>
                <div class="p-8 text-center space-y-1 border-t lg:border-t-0 bg-red-50/30">
                    <div
                        [class]="'text-3xl font-black tracking-tighter ' + (getTotalPixelsChanged() > 0 ? 'text-red-600' : 'text-slate-800')">
                        {{ getTotalPixelsChanged() | number }}
                    </div>
                    <div class="text-[10px] uppercase font-bold text-slate-400 tracking-widest">Pixels Shifted</div>
                </div>
            </div>
        </div>

        <!-- Section Title -->
        <div class="flex items-center gap-4">
            <h2 class="text-2xl font-black text-slate-900 tracking-tight">Pixel Analysis Results</h2>
            <div class="flex-1 h-[2px] bg-slate-100"></div>
            <div class="flex items-center gap-2">
                <span class="w-3 h-3 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.3)]"></span>
                <span class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Live Report</span>
            </div>
        </div>

        <!-- Results Loop -->
        <div class="space-y-20">
            <div *ngFor="let result of results" class="space-y-8">
                <div
                    class="flex flex-col md:flex-row justify-between items-start md:items-end gap-2 border-l-4 border-indigo-600 pl-6 py-2">
                    <div class="space-y-1">
                        <h3 class="text-2xl font-black text-slate-900 tracking-tight">{{ result.route || 'Global Scope'
                            }}</h3>
                        <p class="text-sm font-medium text-slate-400">Deep-scan analysis for primary route node.</p>
                    </div>
                    <div *ngIf="result.requiresAuth"
                        class="px-3 py-1 rounded-lg bg-emerald-50 text-emerald-600 text-[10px] font-black tracking-widest uppercase border border-emerald-100">
                        Authenticated Session
                    </div>
                </div>

                <div *ngIf="result.error"
                    class="p-6 bg-red-50 border border-red-100 rounded-2xl flex items-center gap-4 text-red-600 font-medium animate-fade-in shadow-sm">
                    <div class="w-10 h-10 bg-red-100/50 rounded-xl flex items-center justify-center">
                        <lucide-icon name="x-circle" [size]="20"></lucide-icon>
                    </div>
                    <span>{{ result.error }}</span>
                </div>

                <!-- Viewports Grid -->
                <div class="grid grid-cols-1 gap-12">
                    <div *ngFor="let vpResult of result.viewports"
                        class="premium-card p-0 overflow-hidden bg-slate-50/30">
                        <!-- Viewport Header -->
                        <div class="bg-white p-6 border-b border-slate-100 flex items-center justify-between">
                            <div class="flex items-center gap-4">
                                <div
                                    [class]="'w-12 h-12 rounded-2xl flex items-center justify-center transition-shadow shadow-sm ' + 
                                  (vpResult.viewport === 'Desktop' ? 'bg-indigo-50 text-indigo-600' : 'bg-purple-50 text-purple-600')">
                                    <lucide-icon
                                        [name]="vpResult.viewport === 'Desktop' ? 'monitor' : (vpResult.viewport === 'Tablet' ? 'tablet' : 'smartphone')"
                                        [size]="24"></lucide-icon>
                                </div>
                                <div>
                                    <h4 class="font-bold text-slate-900 text-lg leading-tight">{{ vpResult.viewport }}
                                    </h4>
                                    <p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">{{
                                        vpResult.width }} × {{ vpResult.height }} Resolution {{ vpResult.viewport }}
                                    </p>
                                </div>
                            </div>
                            <div class="text-right">
                                <div class="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Status
                                </div>
                                <div class="font-black text-lg text-emerald-500">OPTIMAL</div>
                            </div>
                        </div>

                        <div class="p-8 space-y-12">
                            <!-- Full Page Result -->
                            <div *ngIf="vpResult.fullPage">
                                <ng-container
                                    *ngTemplateOutlet="comparisonBlock; context: { title: 'Full Page Master', data: vpResult.fullPage, isMain: true }"></ng-container>
                            </div>

                            <!-- Component Results -->
                            <div *ngIf="vpResult.components?.length > 0" class="pt-12 border-t border-slate-200/60">
                                <div class="flex items-center gap-3 mb-10">
                                    <div class="w-1 h-6 bg-indigo-500 rounded-full"></div>
                                    <h5 class="text-lg font-black text-slate-800 tracking-tight">Component Breakdown
                                    </h5>
                                    <span
                                        class="px-2 py-0.5 rounded-md bg-indigo-50 text-indigo-600 text-[10px] font-bold">{{
                                        vpResult.components.length }}</span>
                                </div>
                                <div class="space-y-24">
                                    <div *ngFor="let comp of vpResult.components">
                                        <ng-container
                                            *ngTemplateOutlet="comparisonBlock; context: { title: comp.name, data: comp, isMain: false }"></ng-container>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </ng-container>
</div>

<!-- Reusable Comparison Block Template -->
<ng-template #comparisonBlock let-title="title" let-data="data" let-isMain="isMain">
    <div class="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-8 group">
        <div class="space-y-1">
            <h5
                [class]="'font-black tracking-tight ' + (isMain ? 'text-2xl text-slate-900' : 'text-xl text-slate-700')">
                {{ title }}
            </h5>
            <p class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{{ isMain ? 'Primary Site
                Snapshot' : 'UI Module Isolation' }}</p>
        </div>
        <div class="flex flex-wrap items-center gap-6">
            <div *ngIf="data.accuracy" class="text-right space-y-0.5">
                <div class="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Match Precision</div>
                <div class="flex items-baseline gap-1">
                    <span
                        [class]="'text-2xl font-black ' + (data.accuracy > 99 ? 'text-emerald-600' : 'text-amber-600')">{{
                        data.accuracy }}%</span>
                </div>
            </div>
            <div *ngIf="data.diffPixels !== undefined" class="text-right space-y-0.5">
                <div class="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Pixels Changed</div>
                <div class="flex items-baseline gap-1">
                    <span
                        [class]="'text-2xl font-black ' + (data.diffPixels > 0 ? 'text-red-600' : 'text-slate-900')">{{
                        data.diffPixels | number }}</span>
                </div>
            </div>
            <div class="w-[1px] h-8 bg-slate-200 hidden md:block"></div>
            <div class="flex flex-col items-end gap-1.5">
                <div class="text-[10px] font-bold text-slate-400 uppercase tracking-tighter">Analysis Result</div>
                <span
                    [class]="'px-3 py-1 rounded-full text-[10px] font-black uppercase border shadow-sm ' + getStatusColor(data?.status)">
                    {{ formatStatus(data?.status) }}
                </span>
            </div>
        </div>
    </div>

    <!-- Image Board -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <ng-container *ngTemplateOutlet="imageBox; context: { label: 'Baseline', src: data.baseline }"></ng-container>
        <ng-container
            *ngTemplateOutlet="imageBox; context: { label: 'Current Capture', src: data.current }"></ng-container>
        <ng-container
            *ngTemplateOutlet="imageBox; context: { label: 'Pixel Difference', src: data.diff, isDiff: true, status: data.status, accuracy: data.accuracy }"></ng-container>
    </div>
</ng-template>

<!-- Reusable Image Box Template -->
<ng-template #imageBox let-label="label" let-src="src" let-isDiff="isDiff" let-status="status" let-accuracy="accuracy">
    <div class="space-y-4">
        <div
            class="flex items-center justify-between text-[10px] font-bold text-slate-400 uppercase tracking-widest pl-1">
            <span class="flex items-center gap-1.5">
                <div
                    [class]="'w-1.5 h-1.5 rounded-full ' + (isDiff ? (accuracy < 100 ? 'bg-red-500' : 'bg-emerald-500') : 'bg-indigo-300')">
                </div>
                {{ label }}
            </span>
            <span *ngIf="src" class="text-indigo-500 hover:text-indigo-700 cursor-pointer transition-colors"
                (click)="openScreenshot(src)">Full View</span>
        </div>

        <!-- Empty Baseline State -->
        <div *ngIf="!src && isDiff && status?.includes('baseline')"
            class="aspect-[4/3] border-2 border-dashed border-indigo-100 rounded-3xl flex flex-col items-center justify-center bg-indigo-50/30 text-indigo-400 overflow-hidden group shadow-inner">
            <div
                class="w-16 h-16 bg-white rounded-2xl shadow-sm flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                <lucide-icon name="image" [size]="24"></lucide-icon>
            </div>
            <span class="text-[10px] font-black uppercase tracking-widest">Ground Truth Set</span>
            <p class="text-[9px] font-medium opacity-60 mt-1">Verification not required.</p>
        </div>

        <!-- General Empty State -->
        <div *ngIf="!src && !(isDiff && status?.includes('baseline'))"
            class="aspect-[4/3] bg-slate-100/50 rounded-3xl flex items-center justify-center text-slate-200 shadow-inner">
            <lucide-icon name="image" [size]="48" class="opacity-30"></lucide-icon>
        </div>

        <!-- Image Card -->
        <div *ngIf="src"
            class="group relative rounded-3xl overflow-hidden border border-slate-200/50 bg-slate-900 shadow-2xl transition-all duration-500 hover:shadow-indigo-500/10">
            <img [src]="getScreenshotUrl(src)" [alt]="label"
                class="w-full h-auto object-contain cursor-zoom-in transition-all duration-700 group-hover:scale-[1.04] opacity-90 group-hover:opacity-100"
                (click)="openScreenshot(src)" />

            <!-- Context Overlay -->
            <div
                class="absolute inset-x-0 bottom-0 p-4 bg-gradient-to-t from-black/80 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none">
                <div class="text-[10px] font-bold text-white uppercase tracking-widest">{{ label }} Preview</div>
            </div>
        </div>
    </div>
</ng-template>

// frontend/src/components/ReportDetail.jsx
import React, { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { getReport, getScreenshotUrl, downloadReport, deleteReport } from '../api';
import { ArrowLeft, CheckCircle, XCircle, Smartphone, Download, Trash2 } from 'lucide-react';

export default function ReportDetail() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        async function load() {
            try {
                const data = await getReport(id);
                setReport(data);
            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        }
        load();
    }, [id]);

    const handleDownload = async () => {
        try {
            const blob = await downloadReport(id);
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `report-${id}.zip`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (error) {
            console.error('Download failed:', error);
            alert('Failed to download report');
        }
    };

    const handleDelete = async () => {
        if (!window.confirm('Are you sure you want to delete this report? This action cannot be undone.')) {
            return;
        }

        try {
            await deleteReport(id);
            alert('Report deleted successfully');
            navigate('/');
        } catch (error) {
            console.error('Delete failed:', error);
            alert('Failed to delete report');
        }
    };

    if (loading) return <div className="p-8 text-center">Loading...</div>;
    if (!report) return <div className="p-8 text-center text-red-500">Report not found</div>;

    return (
        <div className="max-w-6xl mx-auto p-6">
            <Link to="/" className="flex items-center gap-2 text-gray-600 mb-6 hover:text-blue-600">
                <ArrowLeft size={20} /> Back to Home
            </Link>

            <div className="bg-white rounded-xl shadow-lg overflow-hidden mb-8">
                <div className="bg-slate-800 text-white p-8">
                    <div className="flex justify-between items-start mb-2">
                        <h1 className="text-3xl font-bold">{report.site}</h1>
                        <div className="flex gap-2">
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition"
                            >
                                <Download size={18} />
                                Download
                            </button>
                            <button
                                onClick={handleDelete}
                                className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg transition"
                            >
                                <Trash2 size={18} />
                                Delete
                            </button>
                        </div>
                    </div>
                    <p className="text-gray-300 mb-4">{report.url}</p>
                    <div className="flex gap-4">
                        <span className="bg-white/10 px-3 py-1 rounded-full text-sm">
                            {new Date(report.timestamp).toLocaleString()}
                        </span>
                        <span className="bg-white/10 px-3 py-1 rounded-full text-sm">
                            Duration: {report.duration}
                        </span>
                    </div>
                </div>

                {/* Stats Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-6 bg-slate-50 border-b">
                    <StatCard label="Routes Tested" value={report.results.length} />
                    <StatCard label="Total Viewports" value={report.results.reduce((acc, r) => acc + (r.viewports?.length || 0), 0)} />
                    <StatCard label="Screenshots" value={report.results.reduce((acc, r) => {
                        return acc + (r.viewports?.reduce((sum, vp) => sum + 1 + (vp.components?.length || 0), 0) || 0);
                    }, 0)} />
                    <StatCard label="Components" value={report.results.reduce((acc, r) => {
                        return acc + (r.viewports?.reduce((sum, vp) => sum + (vp.components?.length || 0), 0) || 0);
                    }, 0)} />
                </div>
            </div>

            {/* Visual Tests Section */}
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                <CheckCircle className="text-blue-600" /> Comparison Results
            </h2>
            <div className="flex flex-col gap-8 mb-12">
                {report.results.map((result, index) => (
                    <div key={index} className="bg-white rounded-lg shadow-md overflow-hidden border border-gray-100">
                        <div className="p-4 border-b bg-gray-50">
                            <h3 className="font-bold text-gray-800 text-lg">{result.route}</h3>
                        </div>

                        <div className="p-4 space-y-8">
                            {/* Viewport Results */}
                            {result.viewports?.map((vpResult, vpIdx) => (
                                <div key={vpIdx} className="border rounded-lg p-4 bg-slate-50">
                                    <div className="flex items-center gap-3 mb-4">
                                        <span className="text-2xl">
                                            {vpResult.viewport === 'Desktop' ? '🖥️' : vpResult.viewport === 'Tablet' ? '📱' : '📱'}
                                        </span>
                                        <div>
                                            <h4 className="font-bold text-gray-800">{vpResult.viewport}</h4>
                                            <span className="text-xs text-gray-500">{vpResult.width} × {vpResult.height}</span>
                                        </div>
                                    </div>

                                    {/* Full Page Result */}
                                    {vpResult.fullPage && (
                                        <ComparisonBlock
                                            title="Full Page Scan"
                                            data={vpResult.fullPage}
                                            isMain={true}
                                        />
                                    )}

                                    {/* Component Results (Desktop only) */}
                                    {vpResult.components?.length > 0 && (
                                        <div className="border-t mt-4 pt-4">
                                            <h5 className="font-bold text-gray-700 mb-4 flex items-center gap-2">
                                                <span className="w-2 h-6 bg-blue-500 rounded-sm"></span>
                                                Component Analysis
                                            </h5>
                                            <div className="grid grid-cols-1 gap-6">
                                                {vpResult.components.map((comp, idx) => (
                                                    <ComparisonBlock key={idx} title={comp.name} data={comp} />
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            ))}

                            {/* Legacy format support (old reports without viewports) */}
                            {!result.viewports && result.fullPage && (
                                <>
                                    <ComparisonBlock
                                        title="Full Page Scan"
                                        data={result.fullPage}
                                        isMain={true}
                                    />
                                    {result.components?.length > 0 && (
                                        <div className="border-t pt-4">
                                            <h4 className="font-bold text-gray-700 mb-4 flex items-center gap-2">
                                                <span className="w-2 h-6 bg-blue-500 rounded-sm"></span>
                                                Component Analysis
                                            </h4>
                                            <div className="grid grid-cols-1 gap-6">
                                                {result.components.map((comp, idx) => (
                                                    <ComparisonBlock key={idx} title={comp.name} data={comp} />
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </>
                            )}
                        </div>

                        {result.error && (
                            <div className="p-4 bg-red-50 text-red-700 border-t border-red-100">
                                Error: {result.error}
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
}

function ComparisonBlock({ title, data, isMain = false }) {
    if (!data) return null;

    // Status Badge Color
    const statusColor =
        data.status === 'pass' ? 'bg-green-100 text-green-700 border-green-200' :
            data.status === 'fail' ? 'bg-red-100 text-red-700 border-red-200' :
                data.status.includes('baseline') ? 'bg-blue-100 text-blue-700 border-blue-200' :
                    'bg-gray-100 text-gray-700';

    return (
        <div className={`rounded-xl ${isMain ? 'bg-slate-50 p-4 border border-slate-200' : 'bg-white'}`}>
            <div className="flex justify-between items-center mb-3">
                <h5 className={`font-semibold ${isMain ? 'text-xl' : 'text-lg text-gray-700'}`}>{title}</h5>
                <div className="flex items-center gap-3">
                    {data.accuracy && (
                        <div className="text-sm font-mono text-gray-600 flex flex-col items-end">
                            <span>Accuracy: <strong className="text-green-600">{data.accuracy}%</strong></span>
                            {data.totalPixels && (
                                <span className="text-xs text-gray-500">
                                    {data.matchingPixels?.toLocaleString()} / {data.totalPixels?.toLocaleString()} pixels match
                                </span>
                            )}
                            {data.diffPixels > 0 && (
                                <span className="text-xs text-red-600">
                                    {data.diffPixels?.toLocaleString()} pixels differ
                                </span>
                            )}
                        </div>
                    )}
                    <span className={`px-2 py-0.5 rounded text-xs font-bold uppercase border ${statusColor}`}>
                        {data.status.replace('_', ' ')}
                    </span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Imagebox label="Baseline" src={data.baseline} />
                <Imagebox label="Current" src={data.current} />
                <Imagebox label="Diff" src={data.diff} isDiff={true} status={data.status} />
            </div>
        </div>
    );
}

function Imagebox({ label, src, isDiff = false, status }) {
    if (!src && isDiff && status?.includes('baseline')) {
        return (
            <div className="border border-dashed rounded h-40 flex items-center justify-center bg-gray-50. text-gray-400 text-sm">
                Baseline Created
            </div>
        );
    }

    if (!src) return <div className="h-40 bg-gray-100 rounded"></div>;

    return (
        <div>
            <div className="text-xs text-center text-gray-500 mb-1 uppercase tracking-wider">{label}</div>
            <div className="border rounded overflow-hidden shadow-sm hover:shadow-md transition bg-white">
                <img
                    src={getScreenshotUrl(src)}
                    alt={label}
                    className="w-full h-auto cursor-pointer hover:scale-[1.02] transition-transform duration-200"
                    onClick={() => window.open(getScreenshotUrl(src), '_blank')}
                />
            </div>
        </div>
    );
}

function StatCard({ label, value }) {
    return (
        <div className="bg-white p-4 rounded-lg text-center shadow-sm">
            <div className="text-2xl font-bold text-gray-800">{value}</div>
            <div className="text-xs text-uppercase text-gray-500 font-semibold">{label}</div>
        </div>
    )
}
