// angular-frontend/src/app/components/test-form/test-form.component.ts
import { Component, EventEmitter, Output, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { LucideAngularModule, Play, Loader2, Plus, Shield, ShieldOff, X } from 'lucide-angular';
import { Subject, Subscription } from 'rxjs';
import { debounceTime, distinctUntilChanged } from 'rxjs/operators';

@Component({
    selector: 'app-test-form',
    standalone: true,
    imports: [CommonModule, FormsModule, LucideAngularModule],
    templateUrl: './test-form.component.html'
})
export class TestFormComponent implements OnInit, OnDestroy {
    @Output() testComplete = new EventEmitter<any>();

    url = '';
    domain = '';
    availableRoutes: string[] = [];
    selectedRoutes: string[] = ['/'];
    newRoute = '';
    loading = false;
    error: string | null = null;

    // Authentication state
    requiresAuth = false;
    mobile = '';
    password = '';
    customHeaders: any = {};

    private urlSubject = new Subject<string>();
    private urlSubscription?: Subscription;

    constructor(private apiService: ApiService) { }

    ngOnInit() {
        this.urlSubscription = this.urlSubject.pipe(
            debounceTime(300),
            distinctUntilChanged()
        ).subscribe(url => {
            this.handleUrlChange(url);
        });
    }

    ngOnDestroy() {
        this.urlSubscription?.unsubscribe();
    }

    onUrlInput() {
        this.urlSubject.next(this.url);
    }

    handleUrlChange(url: string) {
        if (url) {
            try {
                const urlObj = new URL(url);
                const extractedDomain = urlObj.hostname;
                this.domain = extractedDomain;
                this.loadRoutes(extractedDomain);
                this.loadAuthConfig(extractedDomain);
            } catch (e) {
                this.domain = '';
                this.availableRoutes = [];
            }
        } else {
            this.domain = '';
            this.availableRoutes = [];
        }
    }

    loadAuthConfig(domain: string) {
        this.apiService.getAuthConfig(domain).subscribe({
            next: (config) => {
                this.requiresAuth = config.requiresAuth || false;
                this.mobile = config.mobile || '';
                this.password = config.password || '';
                this.customHeaders = config.customHeaders || {};
            },
            error: (err) => console.error('Failed to load auth config:', err)
        });
    }

    loadRoutes(domain: string) {
        this.apiService.getRoutes(domain).subscribe({
            next: (routes) => {
                this.availableRoutes = routes;
                // If / exists in available routes, make sure it's selected by default if nothing else is
                if (routes.includes('/') && this.selectedRoutes.length === 0) {
                    this.selectedRoutes = ['/'];
                }
            },
            error: (err) => console.error('Failed to load routes:', err)
        });
    }

    toggleRoute(route: string) {
        if (this.selectedRoutes.includes(route)) {
            this.selectedRoutes = this.selectedRoutes.filter(r => r !== route);
        } else {
            this.selectedRoutes = [...this.selectedRoutes, route];
        }
    }

    handleAddRoute() {
        if (!this.newRoute.trim() || !this.domain) return;
        const route = this.newRoute.trim();

        this.apiService.saveRoute(this.domain, route).subscribe({
            next: (updatedRoutes) => {
                this.availableRoutes = updatedRoutes;
                this.selectedRoutes = [...this.selectedRoutes, route];
                this.newRoute = '';
            },
            error: (err) => console.error('Failed to save route:', err)
        });
    }

    handleDeleteRoute(routeToDelete: string) {
        if (routeToDelete === '/' && this.availableRoutes.length === 1) {
            alert('Cannot delete the last route');
            return;
        }

        if (!window.confirm(`Delete route "${routeToDelete}"?`)) return;

        this.selectedRoutes = this.selectedRoutes.filter(r => r !== routeToDelete);
        this.availableRoutes = this.availableRoutes.filter(r => r !== routeToDelete);
        // Ideally call API to delete route here if backend supports it
    }

    handleSaveAuth() {
        if (!this.domain) return;
        this.apiService.saveAuthConfig(this.domain, {
            requiresAuth: this.requiresAuth,
            mobile: this.mobile,
            password: this.password,
            customHeaders: this.customHeaders
        }).subscribe({
            error: (err) => console.error('Failed to save auth config:', err)
        });
    }

    toggleAuth() {
        this.requiresAuth = !this.requiresAuth;
        this.handleSaveAuth();
    }

    handleSubmit() {
        if (this.selectedRoutes.length === 0) {
            this.error = 'Please select at least one route';
            return;
        }

        this.loading = true;
        this.error = null;

        const authConfig = {
            requiresAuth: this.requiresAuth,
            mobile: this.mobile,
            password: this.password,
            customHeaders: this.customHeaders
        };

        this.apiService.runTest(this.url, this.selectedRoutes, authConfig).subscribe({
            next: (report) => {
                this.testComplete.emit(report);
                this.url = '';
                this.selectedRoutes = ['/'];
                this.loading = false;
            },
            error: (err) => {
                this.error = err.error?.error || err.message;
                this.loading = false;
            }
        });
    }
}

<div class="glass-card overflow-hidden">
    <div class="p-8 space-y-8">
        <div class="flex items-center justify-between">
            <div>
                <h2 class="text-2xl font-bold text-slate-900">New Visual Test</h2>
                <p class="text-slate-500 text-sm">Enter a URL to begin automated visual analysis.</p>
            </div>
            <div class="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center text-indigo-600">
                <lucide-icon name="play" [size]="24"></lucide-icon>
            </div>
        </div>

        <form (submit)="handleSubmit(); $event.preventDefault()" class="space-y-6">
            <div class="space-y-2">
                <label class="text-sm font-bold text-slate-700 ml-1 uppercase tracking-wider">Website URL</label>
                <div class="relative group">
                    <div
                        class="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-slate-400 group-focus-within:text-indigo-600 transition-colors">
                        <lucide-icon name="globe" [size]="18"></lucide-icon>
                    </div>
                    <input type="url" required placeholder="https://example.com" [(ngModel)]="url" name="url"
                        (input)="onUrlInput()"
                        class="w-full pl-12 pr-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:bg-white focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/5 transition-all outline-none text-lg font-medium" />
                </div>
            </div>

            <ng-container *ngIf="domain">
                <!-- Configuration Grid -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-in">

                    <!-- Authentication Section -->
                    <div class="premium-card p-6 bg-slate-50/50">
                        <div class="flex items-center justify-between mb-6">
                            <div class="flex items-center gap-3">
                                <div
                                    [class]="'w-10 h-10 rounded-xl flex items-center justify-center ' + (requiresAuth ? 'bg-emerald-100 text-emerald-600' : 'bg-slate-200 text-slate-400')">
                                    <lucide-icon [name]="requiresAuth ? 'shield' : 'shield-off'"
                                        [size]="20"></lucide-icon>
                                </div>
                                <div>
                                    <h3 class="font-bold text-slate-900">Authentication</h3>
                                    <p class="text-xs text-slate-500">{{ requiresAuth ? 'Active' : 'Disabled' }}</p>
                                </div>
                            </div>
                            <button type="button" (click)="toggleAuth()"
                                [class]="'relative inline-flex h-6 w-11 items-center rounded-full transition-all duration-300 ' + (requiresAuth ? 'bg-emerald-500' : 'bg-slate-300')">
                                <span
                                    [class]="'inline-block h-4 w-4 transform rounded-full bg-white transition-transform duration-300 shadow-sm ' + (requiresAuth ? 'translate-x-6' : 'translate-x-1')"></span>
                            </button>
                        </div>

                        <div *ngIf="requiresAuth" class="space-y-4 animate-fade-in">
                            <div class="space-y-1">
                                <label class="text-xs font-bold text-slate-500 ml-1 uppercase tracking-tighter">Mobile
                                    Number</label>
                                <input type="tel" placeholder="Enter mobile number" [(ngModel)]="mobile" name="mobile"
                                    (blur)="handleSaveAuth()"
                                    class="w-full p-3 bg-white border border-slate-100 rounded-xl focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 outline-none transition-all text-sm" />
                            </div>
                            <div class="space-y-1">
                                <label
                                    class="text-xs font-bold text-slate-500 ml-1 uppercase tracking-tighter">Password</label>
                                <input type="password" placeholder="Enter password" [(ngModel)]="password"
                                    name="password" (blur)="handleSaveAuth()"
                                    class="w-full p-3 bg-white border border-slate-100 rounded-xl focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 outline-none transition-all text-sm" />
                            </div>
                        </div>

                        <p *ngIf="!requiresAuth" class="text-xs text-slate-400 italic">Enable to test logged-in areas.
                        </p>
                    </div>

                    <!-- Routes Section -->
                    <div class="premium-card p-6 bg-slate-50/50 flex flex-col">
                        <h3 class="font-bold text-slate-900 mb-4 flex items-center gap-2">
                            <lucide-icon name="external-link" [size]="18" class="text-indigo-600"></lucide-icon>
                            Test Routes
                        </h3>

                        <div class="flex flex-wrap gap-1.5 mb-4 overflow-y-auto max-h-32 pr-2 custom-scrollbar">
                            <div *ngFor="let route of availableRoutes" class="relative group">
                                <button type="button" (click)="toggleRoute(route)"
                                    [class]="'px-3 py-1.5 pr-8 rounded-lg text-xs font-bold transition-all border ' + (selectedRoutes.includes(route) ? 'bg-indigo-600 border-indigo-600 text-white shadow-md shadow-indigo-100' : 'bg-white border-slate-100 text-slate-600 hover:border-indigo-200 group-hover:bg-indigo-50')">
                                    {{ route }}
                                </button>
                                <button type="button" (click)="handleDeleteRoute(route); $event.stopPropagation()"
                                    [class]="'absolute right-1 top-1/2 -translate-y-1/2 p-1 rounded-md transition-opacity ' + (selectedRoutes.includes(route) ? 'text-white/80 hover:text-white' : 'text-slate-300 hover:text-red-500')"
                                    title="Delete route">
                                    <lucide-icon name="x" [size]="12"></lucide-icon>
                                </button>
                            </div>
                            <div *ngIf="availableRoutes.length === 0" class="text-xs text-slate-400">No routes found
                            </div>
                        </div>

                        <div class="mt-auto flex gap-2">
                            <input type="text" placeholder="/new-route" [(ngModel)]="newRoute" name="newRoute"
                                (keydown.enter)="handleAddRoute(); $event.preventDefault()"
                                class="flex-1 p-2 py-2.5 bg-white border border-slate-100 rounded-xl focus:border-indigo-500 outline-none transition-all text-xs font-medium" />
                            <button type="button" (click)="handleAddRoute()"
                                class="bg-slate-900 text-white p-2.5 rounded-xl hover:bg-slate-800 transition-colors">
                                <lucide-icon name="plus" [size]="16"></lucide-icon>
                            </button>
                        </div>
                    </div>

                </div>

                <div
                    class="flex items-center justify-between px-6 py-4 bg-indigo-50/50 rounded-2xl border border-indigo-100/50">
                    <div class="flex items-center gap-2">
                        <div class="flex -space-x-2">
                            <div *ngFor="let r of selectedRoutes.slice(0, 3)"
                                class="w-6 h-6 rounded-full bg-white border border-indigo-100 flex items-center justify-center text-[10px] font-bold text-indigo-600">
                                {{ r === '/' ? 'H' : r.charAt(1).toUpperCase() }}
                            </div>
                            <div *ngIf="selectedRoutes.length > 3"
                                class="w-6 h-6 rounded-full bg-indigo-600 border border-white flex items-center justify-center text-[10px] font-bold text-white">
                                +{{ selectedRoutes.length - 3 }}
                            </div>
                        </div>
                        <span class="text-xs font-bold text-indigo-900 ml-2">
                            {{ selectedRoutes.length }} route(s) selected
                        </span>
                    </div>
                    <span class="text-[10px] font-bold text-indigo-400 uppercase tracking-widest">Target: {{ domain
                        }}</span>
                </div>
            </ng-container>

            <button type="submit" [disabled]="loading || selectedRoutes.length === 0"
                class="btn-primary w-full py-5 text-lg shadow-xl shadow-indigo-200 group">
                <lucide-icon *ngIf="loading" name="loader-2" class="animate-spin"></lucide-icon>
                <lucide-icon *ngIf="!loading" name="play" [size]="20"
                    class="group-hover:translate-x-1 transition-transform"></lucide-icon>
                {{ loading ? 'Running Visual Engine...' : 'Launch Analysis' }}
            </button>
        </form>

        <div *ngIf="error"
            class="mt-6 p-4 bg-red-50 border border-red-100 text-red-600 rounded-xl text-sm font-medium animate-fade-in flex items-center gap-3">
            <lucide-icon name="shield-off" [size]="18"></lucide-icon>
            Error: {{ error }}
        </div>
    </div>
</div>

// frontend/src/components/TestForm.jsx
import React, { useState, useEffect } from 'react';
import { runTest, getRoutes, saveRoute, getAuthConfig, saveAuthConfig } from '../api';
import { Play, Loader2, Plus, Shield, ShieldOff, X } from 'lucide-react';

export default function TestForm({ onTestComplete }) {
    const [url, setUrl] = useState('');
    const [domain, setDomain] = useState('');
    const [availableRoutes, setAvailableRoutes] = useState([]);
    const [selectedRoutes, setSelectedRoutes] = useState(['/']);
    const [newRoute, setNewRoute] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    // Authentication state
    const [requiresAuth, setRequiresAuth] = useState(false);
    const [mobile, setMobile] = useState('');
    const [password, setPassword] = useState('');
    const [customHeaders, setCustomHeaders] = useState({});

    // Extract domain from URL and load auth config
    useEffect(() => {
        if (url) {
            try {
                const urlObj = new URL(url);
                const extractedDomain = urlObj.hostname;
                setDomain(extractedDomain);
                loadRoutes(extractedDomain);
                loadAuthConfig(extractedDomain);
            } catch (e) {
                setDomain('');
                setAvailableRoutes([]);
            }
        } else {
            setDomain('');
            setAvailableRoutes([]);
        }
    }, [url]);

    const loadAuthConfig = async (domain) => {
        try {
            const config = await getAuthConfig(domain);
            setRequiresAuth(config.requiresAuth || false);
            setMobile(config.mobile || '');
            setPassword(config.password || '');
            setCustomHeaders(config.customHeaders || {});
        } catch (err) {
            console.error('Failed to load auth config:', err);
        }
    };

    const loadRoutes = async (domain) => {
        try {
            const routes = await getRoutes(domain);
            setAvailableRoutes(routes);
            // Auto-select home route
            if (routes.includes('/') && !selectedRoutes.includes('/')) {
                setSelectedRoutes(['/']);
            }
        } catch (err) {
            console.error('Failed to load routes:', err);
        }
    };

    const toggleRoute = (route) => {
        if (selectedRoutes.includes(route)) {
            setSelectedRoutes(selectedRoutes.filter(r => r !== route));
        } else {
            setSelectedRoutes([...selectedRoutes, route]);
        }
    };

    const handleAddRoute = async () => {
        if (!newRoute.trim() || !domain) return;

        const route = newRoute.trim();

        try {
            const updatedRoutes = await saveRoute(domain, route);
            setAvailableRoutes(updatedRoutes);
            setSelectedRoutes([...selectedRoutes, route]);
            setNewRoute('');
        } catch (err) {
            console.error('Failed to save route:', err);
        }
    };

    const handleDeleteRoute = async (routeToDelete) => {
        if (routeToDelete === '/' && availableRoutes.length === 1) {
            alert('Cannot delete the last route');
            return;
        }

        if (!window.confirm(`Delete route "${routeToDelete}"?`)) return;

        try {
            // Remove from selected routes
            setSelectedRoutes(selectedRoutes.filter(r => r !== routeToDelete));
            // Remove from available routes
            const updatedRoutes = availableRoutes.filter(r => r !== routeToDelete);
            setAvailableRoutes(updatedRoutes);

            // Note: You may want to add a backend endpoint to persist this deletion
            // For now, it will be removed from the UI but will reappear on page reload
        } catch (err) {
            console.error('Failed to delete route:', err);
        }
    };

    const handleSaveAuth = async () => {
        if (!domain) return;
        try {
            await saveAuthConfig(domain, {
                requiresAuth,
                mobile,
                password,
                customHeaders
            });
        } catch (err) {
            console.error('Failed to save auth config:', err);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (selectedRoutes.length === 0) {
            setError('Please select at least one route');
            return;
        }

        setLoading(true);
        setError(null);
        try {
            const authConfig = {
                requiresAuth,
                mobile,
                password,
                customHeaders
            };
            const report = await runTest(url, selectedRoutes, authConfig);
            onTestComplete(report);
            setUrl('');
            setSelectedRoutes(['/']);
        } catch (err) {
            setError(err.response?.data?.error || err.message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="bg-white p-6 rounded-lg shadow-md mb-8">
            <h2 className="text-xl font-bold mb-4 text-gray-800">Run Visual Test</h2>
            <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Website URL</label>
                    <input
                        type="url"
                        required
                        placeholder="https://example.com"
                        value={url}
                        onChange={(e) => setUrl(e.target.value)}
                        className="w-full p-3 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                </div>

                {domain && (
                    <>
                        {/* Authentication Section */}
                        <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
                            <div className="flex items-center justify-between mb-3">
                                <label className="flex items-center gap-2 text-sm font-medium text-gray-700">
                                    {requiresAuth ? <Shield className="text-green-600" size={20} /> : <ShieldOff className="text-gray-400" size={20} />}
                                    Authentication
                                </label>
                                <button
                                    type="button"
                                    onClick={() => setRequiresAuth(!requiresAuth)}
                                    className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${requiresAuth ? 'bg-green-600' : 'bg-gray-300'
                                        }`}
                                >
                                    <span
                                        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${requiresAuth ? 'translate-x-6' : 'translate-x-1'
                                            }`}
                                    />
                                </button>
                            </div>

                            {requiresAuth && (
                                <div className="space-y-3">
                                    <div>
                                        <label className="block text-xs font-medium text-gray-600 mb-1">Mobile Number</label>
                                        <input
                                            type="tel"
                                            placeholder="Enter mobile number"
                                            value={mobile}
                                            onChange={(e) => setMobile(e.target.value)}
                                            onBlur={handleSaveAuth}
                                            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-medium text-gray-600 mb-1">Password</label>
                                        <input
                                            type="password"
                                            placeholder="Enter password"
                                            value={password}
                                            onChange={(e) => setPassword(e.target.value)}
                                            onBlur={handleSaveAuth}
                                            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-500 text-sm"
                                        />
                                    </div>
                                    <p className="text-xs text-gray-500 italic bg-blue-50 p-2 rounded">
                                        ℹ️ System will auto-login and capture session for testing
                                    </p>
                                </div>
                            )}

                            {!requiresAuth && (
                                <p className="text-xs text-gray-500 italic">
                                    Toggle ON to test authenticated pages (e.g., my-bets, profile)
                                </p>
                            )}
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Select Routes to Test
                            </label>
                            <div className="flex flex-wrap gap-2 mb-3">
                                {availableRoutes.map((route) => (
                                    <div key={route} className="relative group">
                                        <button
                                            type="button"
                                            onClick={() => toggleRoute(route)}
                                            className={`px-4 py-2 pr-8 rounded-md font-medium transition ${selectedRoutes.includes(route)
                                                ? 'bg-blue-600 text-white'
                                                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                                                }`}
                                        >
                                            {route}
                                        </button>
                                        <button
                                            type="button"
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                handleDeleteRoute(route);
                                            }}
                                            className={`absolute right-1 top-1/2 -translate-y-1/2 p-1 rounded-full transition-opacity ${selectedRoutes.includes(route)
                                                    ? 'text-white hover:bg-blue-700'
                                                    : 'text-gray-500 hover:bg-gray-300'
                                                }`}
                                            title="Delete route"
                                        >
                                            <X size={14} />
                                        </button>
                                    </div>
                                ))}
                            </div>

                            <div className="flex gap-2">
                                <input
                                    type="text"
                                    placeholder="Add custom route (e.g., /about)"
                                    value={newRoute}
                                    onChange={(e) => setNewRoute(e.target.value)}
                                    onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddRoute())}
                                    className="flex-1 p-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
                                />
                                <button
                                    type="button"
                                    onClick={handleAddRoute}
                                    className="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 flex items-center gap-1 text-sm"
                                >
                                    <Plus size={16} />
                                    Add Route
                                </button>
                            </div>
                        </div>

                        <div className="bg-blue-50 p-3 rounded-md">
                            <p className="text-sm text-gray-700">
                                <strong>Selected routes:</strong> {selectedRoutes.length > 0 ? selectedRoutes.join(', ') : 'None'}
                            </p>
                        </div>
                    </>
                )}

                <button
                    type="submit"
                    disabled={loading || selectedRoutes.length === 0}
                    className="bg-blue-600 text-white px-6 py-3 rounded-md font-semibold hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                    {loading ? <Loader2 className="animate-spin" /> : <Play size={20} />}
                    {loading ? 'Running Visual Tests...' : 'Run Test'}
                </button>
            </form>
            {error && (
                <div className="mt-4 p-4 bg-red-50 text-red-700 rounded-md">
                    Error: {error}
                </div>
            )}
        </div>
    );
}
