// frontend/src/components/ReportList.jsx
import React, { useEffect, useState } from 'react';
import { getReports, deleteReport } from '../api';
import { FileText, Clock, ExternalLink, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function ReportList() {
    const [reports, setReports] = useState([]);

    useEffect(() => {
        loadReports();
    }, []);

    const loadReports = async () => {
        try {
            const data = await getReports();
            setReports(data);
        } catch (err) {
            console.error('Failed to load reports', err);
        }
    };

    const handleDelete = async (reportId, reportSite) => {
        if (!window.confirm(`Are you sure you want to delete the report for "${reportSite}"? This action cannot be undone.`)) {
            return;
        }

        try {
            await deleteReport(reportId);
            alert('Report deleted successfully');
            loadReports(); // Refresh the list
        } catch (error) {
            console.error('Delete failed:', error);
            alert('Failed to delete report');
        }
    };

    return (
        <div className="bg-white p-6 rounded-lg shadow-md">
            <h2 className="text-xl font-bold mb-4 text-gray-800 flex items-center gap-2">
                <FileText /> Recent Reports
            </h2>
            <div className="space-y-4">
                {reports.length === 0 ? (
                    <p className="text-gray-500">No reports found.</p>
                ) : (
                    reports.map((report) => (
                        <div key={report.id} className="border p-4 rounded-md hover:bg-gray-50 transition">
                            <div className="flex justify-between items-start">
                                <div>
                                    <h3 className="font-semibold text-lg text-blue-600">{report.site}</h3>
                                    <p className="text-gray-600 text-sm mt-1">{report.url}</p>
                                </div>
                                <div className="flex gap-2">
                                    <Link
                                        to={`/report/${report.id}`}
                                        className="bg-gray-100 text-gray-700 px-3 py-1 rounded hover:bg-gray-200 text-sm flex items-center gap-1"
                                    >
                                        View <ExternalLink size={14} />
                                    </Link>
                                    <button
                                        onClick={() => handleDelete(report.id, report.site)}
                                        className="bg-red-100 text-red-700 px-3 py-1 rounded hover:bg-red-200 text-sm flex items-center gap-1"
                                    >
                                        <Trash2 size={14} />
                                    </button>
                                </div>
                            </div>
                            <div className="flex gap-4 mt-3 text-sm text-gray-500">
                                <span className="flex items-center gap-1">
                                    <Clock size={14} />
                                    {new Date(report.timestamp).toLocaleString()}
                                </span>
                                <span>Duration: {report.duration}</span>
                                <span>Routes: {report.results?.length || report.tests?.length || 0}</span>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}

// angular-frontend/src/app/components/report-list/report-list.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { LucideAngularModule, FileText, Clock, ExternalLink, Trash2 } from 'lucide-angular';

@Component({
    selector: 'app-report-list',
    standalone: true,
    imports: [CommonModule, RouterModule, LucideAngularModule],
    templateUrl: './report-list.component.html'
})
export class ReportListComponent implements OnInit, OnChanges {
    @Input() refreshKey = 0;
    reports: any[] = [];

    constructor(private apiService: ApiService) { }

    ngOnInit() {
        this.loadReports();
    }

    ngOnChanges(changes: SimpleChanges) {
        if (changes['refreshKey'] && !changes['refreshKey'].firstChange) {
            this.loadReports();
        }
    }

    loadReports() {
        this.apiService.getReports().subscribe({
            next: (data) => this.reports = data,
            error: (err) => console.error('Failed to load reports', err)
        });
    }

    handleDelete(reportId: string, reportSite: string) {
        if (!window.confirm(`Are you sure you want to delete the report for "${reportSite}"? This action cannot be undone.`)) {
            return;
        }

        this.apiService.deleteReport(reportId).subscribe({
            next: () => {
                alert('Report deleted successfully');
                this.loadReports();
            },
            error: (err) => {
                console.error('Delete failed:', err);
                alert('Failed to delete report');
            }
        });
    }
}

<div class="space-y-8 animate-fade-in">
    <div class="flex items-center justify-between">
        <h2 class="text-2xl font-bold text-slate-900 flex items-center gap-3">
            <div class="w-10 h-10 bg-slate-100 rounded-xl flex items-center justify-center text-slate-600">
                <lucide-icon name="file-text" [size]="20"></lucide-icon>
            </div>
            Analysis History
        </h2>
        <div
            class="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white border border-slate-100 shadow-sm text-xs font-bold text-slate-500">
            <div class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
            {{ reports.length }} Total Reports
        </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <!-- Empty State -->
        <div *ngIf="reports.length === 0"
            class="col-span-full py-20 premium-card flex flex-col items-center justify-center text-center space-y-4">
            <div class="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center text-slate-200">
                <lucide-icon name="image" [size]="40"></lucide-icon>
            </div>
            <div>
                <h3 class="font-bold text-slate-900">No reports yet</h3>
                <p class="text-slate-500 text-sm">Run your first test to see analysis results here.</p>
            </div>
        </div>

        <!-- Report Card -->
        <div *ngFor="let report of reports" class="premium-card group">
            <div class="p-6 space-y-6">
                <div class="flex justify-between items-start">
                    <div class="space-y-1">
                        <h3
                            class="font-bold text-slate-900 group-hover:text-indigo-600 transition-colors truncate max-w-[180px]">
                            {{ report.site }}
                        </h3>
                        <p class="text-xs text-slate-400 font-medium truncate max-w-[180px]">{{ report.url }}</p>
                    </div>
                    <button (click)="handleDelete(report.id, report.site)"
                        class="w-8 h-8 rounded-lg flex items-center justify-center text-slate-300 hover:text-red-600 hover:bg-red-50 transition-all">
                        <lucide-icon name="trash-2" [size]="16"></lucide-icon>
                    </button>
                </div>

                <div class="grid grid-cols-2 gap-4">
                    <div class="p-3 bg-slate-50 rounded-xl space-y-1 border border-slate-100/50">
                        <div class="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Routes</div>
                        <div class="text-sm font-bold text-slate-700">{{ report.results?.length || report.tests?.length
                            || 0 }} tested</div>
                    </div>
                    <div class="p-3 bg-slate-50 rounded-xl space-y-1 border border-slate-100/50">
                        <div class="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Duration</div>
                        <div class="text-sm font-bold text-slate-700">{{ report.duration || '0s' }}</div>
                    </div>
                </div>

                <div class="flex items-center justify-between pt-4 border-t border-slate-50">
                    <span class="text-[10px] font-bold text-slate-400 flex items-center gap-1 uppercase tracking-tight">
                        <lucide-icon name="clock" [size]="12"></lucide-icon>
                        {{ report.timestamp | date:'MMM d, HH:mm' }}
                    </span>
                    <a [routerLink]="['/report', report.id]"
                        class="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-50 text-indigo-600 rounded-lg text-xs font-bold hover:bg-indigo-600 hover:text-white transition-all shadow-sm">
                        Analysis results <lucide-icon name="external-link" [size]="12"></lucide-icon>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
